stages:
  - build
  - test
  - sonar-scan
  - deploy

build:
  stage: build
  tags:
    - prod
  script:
    - echo "dasdas"

test:
  stage: test
  tags:
    - prod
  script:
    - echo 'testing'

sonar-scan:
  stage: sonar-scan
  image: maven:3.8.3-openjdk-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  tags:
    - prod
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=javapro_team26_backend_AYKCbGiS_BNLy3Kxz_em
  allow_failure: true
  only:
    - master
    - dev
    - 12_CI/CD

deploy:
  stage: deploy
  tags:
    - prod
  script:
    - echo 'deploying'