image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

stages:
  - build
  - test
  - sonar-scan
  - package
  - deploy

build:
  stage: build
  only:
#    - dev
#    - master
#    - 12_CI/CD
  tags:
    - prod
  script:
    - mvn compile
  cache:
    paths:
      - ./target
      - ./.m2

test:
  stage: test
  tags:
    - prod
  script:
    - echo 'testing'
#    - mvn test

sonar-scan:
  stage: sonar-scan
  image: maven:3.8.3-openjdk-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  tags:
    - prod
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=javapro_team26_backend_AYKCbGiS_BNLy3Kxz_em
  allow_failure: true
#  only:
#    - master
#    - dev
#    - 12_CI/CD

package:
  stage: package
#  only:
#    - dev
#    - master
  tags:
    - prod
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - ./target
      - ./.m2

deploy:
  stage: deploy
#  only:
#    - dev
#    - master
  tags:
    - prod
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
#    - eval $(ssh-agent -s)
    - echo "check1" | ssh-add -
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#    - ssh-keyscan $DEV_HOST >> ~/.ssh/known_hosts
#    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo 'check2'
#    - ssh root@195.161.114.18 "[ ! -f target/zero-0.0.1-SNAPSHOT.jar ] || mv target/zero-0.0.1-SNAPSHOT.jar target/app-build-app.jar"
#    - scp target/app.jar $DEV_USER@$DEV_HOST:$DEV_APP_PATH/
#    - ssh $DEV_USER@$DEV_HOST "sudo systemctl stop app_service && sudo systemctl start app_service"