spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&stringtype=unspecified
    username: postgres
    password: 1234567890
  redis:
    host: localhost
    password: 1234567890
    port: 6379
  mail:
    host: smtp.mail.ru
    username: zerone.mail@mail.ru
    password: hcaPst9hn8USn45TkqLW
    port: 465
    protocol: smtps
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    session:
      tracking-modes: cookie
  port: 8086

config:
  frontend: "localhost:80"
  backend: "localhost:8086"
  token-validity-hours: 72
  authorization: "AUTHORIZATION"
  secret: SocialNetwork26
  zeroneEmail: zerone.mail@mail.ru
  jwt-black-list-on: false

socketio:
  host: localhost
  port: 1111
  maxFramePayloadLength: 1048576
  maxHttpContentLength: 1048576
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 1000000
  pingTimeout: 6000000
  pingInterval: 25000