#Session security
auth:
  secret: SocialNetwork26
header:
  authorization: "AUTHORIZATION"
server:
  servlet:
    session:
      tracking-modes: cookie


#spring security session login
spring:
  security:
    user:
      name: coder
      password: coder

  #connect to DB
  datasource:
    url: jdbc:postgresql://localhost:5432/soc_net
    username: postgres
    password: Hfnfg123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false
  web:
    resources:
      static-locations: [classpath:/templates/]










