server.port: ${PORT:8080}
spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:${DATABASE_URL:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
  username: ${DATABASE_USERNAME:root}
  password: ${DATABASE_PASSWORD:root}

spring:
  jpa:
    #show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect