spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soc_net
    username: postgres
    password: Hfnfg123

server:
  port: 8086

config:
  frontend: "195.161.62.32:8082"
  backend: "localhost:8086"
  kafkaMailingService: false

logging:
  file:
    path: logs
  level:
    ru.example.group.main: info





