
spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:6432/postgres?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${DATABASE_USERNAME:zerone}
    password: ${DATABASE_PASSWORD:7tsfft}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.mail.ru
    username: zerone.mail@mail.ru
    password: hcaPst9hn8USn45TkqLW
    port: 465
    protocol: smtps
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true

server:
  servlet:
    session:
      tracking-modes: cookie
  port: ${PORT:8080}

config:
  frontend: "195.161.114.18:80"
  backend: "195.161.114.18:8086"
  token-validity-hours: 72
  authorization: "AUTHORIZATION"
  secret: SocialNetwork26
  zeroneEmail: zerone.mail@mail.ru

logging:
  charset:
    console: UTF-8
  file:
    path: logs
  level:
    ru.example.group.main: debug







