spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soc_net
    username: postgres
    password: Hfnfg123

  kafka:
    bootstrap-servers: "localhost:29092"

server:
  port: 8086

config:
  kafkaMailingService: false
  frontend: "http://195.161.62.32:8082"
  backend: "http://localhost:8086"


logging:
  file:
    path: logs
  level:
    ru.example.group.main: info





