spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soc_net
    username: postgres
    password: Hfnfg123
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    session:
      tracking-modes: cookie
      persistent: false
  port: 8086

#spring security session login
  security:
    user:
      name: coder
      password: coder

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
  web:
    resources:
      static-locations: [classpath:/templates/]

#mail settings
  mail:
    host: smtp.mail.ru
    username: zerone.mail@mail.ru
    password: hcaPst9hn8USn45TkqLW
    port: 465
    protocol: smtps
mail:
    #hostBack: "195.161.114.18:8086"
    #hostFront: "195.161.114.18:80"
    hostBack: "localhost:8086"
    hostFront: "localhost:80"

config:
  domain: "195.161.114.18:8082"
  token-validity-hours: 72
  authorization: "AUTHORIZATION"
  secret: SocialNetwork26










