spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soc_net
    username: postgres
    password: Hfnfg123
    driver-class-name: org.postgresql.Driver

server:
  port: 8086

config:
  frontend: "195.161.114.18:8082"
  backend: "localhost:8086"







