#Session security
auth:
  secret: SocialNetwork26
header:
  authorization: "AUTHORIZATION"
server:
  servlet:
    session:
      tracking-modes: cookie
      persistent: false
  port: 8086


#spring security session login
spring:
  security:
    user:
      name: coder
      password: coder

#connect to DB
  datasource:
    url: jdbc:postgresql://localhost:5432/soc_net
    username: postgres
    password: Hfnfg123

    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
  web:
    resources:
      static-locations: [classpath:/templates/]

#mail settings
  mail:
    host: smtp.mail.ru
    username: zerone.mail@mail.ru
    password: hcaPst9hn8USn45TkqLW
    port: 465
    protocol: smtps

mail:
    hostBack: "localhost:8086"
    hostFront: "localhost:80"

#front
front:
  domen: "195.161.114.18:8082"

config:
  domen: "195.161.114.18:8082"









