
spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.mail.ru
    username: zerone.mail@mail.ru
    password: hcaPst9hn8USn45TkqLW
    port: 465
    protocol: smtps
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    session:
      tracking-modes: cookie
  port: ${PORT:8080}


config:
  frontend: "195.161.114.18"
  backend: "195.161.114.18:8086"
  token-validity-hours: 72
  authorization: "AUTHORIZATION"
  secret: SocialNetwork26
  zeroneEmail: zerone.mail@mail.ru
  jwt-black-list-on: false

logging:
  charset:
    console: UTF-8
  file:
    path: logs
  level:
    ru.example.group.main: debug

cloudinary:
  cloud_name: "permishin"
  api_key: "957437892123721"
  api_secret: "MY6piT21gBB0yEsuZFpg-vzRE0Y"
  default_avatar: "https://res.cloudinary.com/permishin/image/upload/v1661419094/default_avatar_ygvgg2.svg"

vk:
  userId: 51412309
  accessToken: "639a1a5d639a1a5d639a1a5dc8608a67086639a639a1a5d009194418ce14b4433e01161"


post:
  time:
    Life:
      Auto-Delete: 31






