spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/zerone
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
#    liquibase:
#      change-log: classpath:db/changelog/dbchangelog.xml
#      enabled: true
  liquibase:
    enabled: false
  mail:
    host: smtp.mail.ru
    username: zerone.mail@mail.ru
    password: UjCdaUFj8QwMhzMwRnbC
    port: 465
    protocol: smtps

server:
  port: 8086

mail:
  host: http://localhost:8086
  debug: true



