spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root

server:
  port: 8086

config:
  frontend: "195.161.114.18:8082"
  backend: "localhost:8086"

